// Last updated: 2024-02-16T15:04:09.753Z

type AICostModel = {
    maxTokens: number | null
    name: string
    type: string
    inputCost: number | null
    inputCostUnit: string | null
    outputCost: number | null
    outputCostUnit: string | null
}

export type AICostModelProvider = 'openai' | 'azure' | 'text-completion-openai' | 'anthropic' | 'mistral' | 'vertex-ai' | 'vertex_ai-code-chat-models' | 'cohere' | 'replicate' | 'openrouter' | 'ai21' | 'nlp_cloud' | 'aleph_alpha' | 'bedrock' | 'sagemaker' | 'ollama' | 'deepinfra' | 'perplexity' | 'anyscale' | 'cloudflare' | 'voyage'

// Generated from LiteLLM
export const AICostModelList = {
    'openai': [
        {
            maxTokens: 8192,
            name: 'gpt-4' as const,
            type: 'chat',
            inputCost: 0.00003,
            inputCostUnit: 'token',
            outputCost: 0.00006,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'gpt-4-turbo-preview' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'gpt-4-0314' as const,
            type: 'chat',
            inputCost: 0.00003,
            inputCostUnit: 'token',
            outputCost: 0.00006,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'gpt-4-0613' as const,
            type: 'chat',
            inputCost: 0.00003,
            inputCostUnit: 'token',
            outputCost: 0.00006,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'gpt-4-32k' as const,
            type: 'chat',
            inputCost: 0.00006,
            inputCostUnit: 'token',
            outputCost: 0.00012,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'gpt-4-32k-0314' as const,
            type: 'chat',
            inputCost: 0.00006,
            inputCostUnit: 'token',
            outputCost: 0.00012,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'gpt-4-32k-0613' as const,
            type: 'chat',
            inputCost: 0.00006,
            inputCostUnit: 'token',
            outputCost: 0.00012,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 128000,
            name: 'gpt-4-1106-preview' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 128000,
            name: 'gpt-4-0125-preview' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 128000,
            name: 'gpt-4-vision-preview' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 128000,
            name: 'gpt-4-1106-vision-preview' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4097,
            name: 'gpt-3.5-turbo' as const,
            type: 'chat',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4097,
            name: 'gpt-3.5-turbo-0301' as const,
            type: 'chat',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4097,
            name: 'gpt-3.5-turbo-0613' as const,
            type: 'chat',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16385,
            name: 'gpt-3.5-turbo-1106' as const,
            type: 'chat',
            inputCost: 0.000001,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16385,
            name: 'gpt-3.5-turbo-0125' as const,
            type: 'chat',
            inputCost: 5e-7,
            inputCostUnit: 'token',
            outputCost: 0.0000015,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16385,
            name: 'gpt-3.5-turbo-16k' as const,
            type: 'chat',
            inputCost: 0.000003,
            inputCostUnit: 'token',
            outputCost: 0.000004,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16385,
            name: 'gpt-3.5-turbo-16k-0613' as const,
            type: 'chat',
            inputCost: 0.000003,
            inputCostUnit: 'token',
            outputCost: 0.000004,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4097,
            name: 'ft:gpt-3.5-turbo' as const,
            type: 'chat',
            inputCost: 0.000003,
            inputCostUnit: 'token',
            outputCost: 0.000006,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8191,
            name: 'text-embedding-3-large' as const,
            type: 'embedding',
            inputCost: 1.3e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 8191,
            name: 'text-embedding-3-small' as const,
            type: 'embedding',
            inputCost: 2e-8,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 8191,
            name: 'text-embedding-ada-002' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 8191,
            name: 'text-embedding-ada-002-v2' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
    ],
    'azure': [
        {
            maxTokens: 128000,
            name: 'azure/gpt-4-0125-preview' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 128000,
            name: 'azure/gpt-4-1106-preview' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'azure/gpt-4-0613' as const,
            type: 'chat',
            inputCost: 0.00003,
            inputCostUnit: 'token',
            outputCost: 0.00006,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'azure/gpt-4-32k-0613' as const,
            type: 'chat',
            inputCost: 0.00006,
            inputCostUnit: 'token',
            outputCost: 0.00012,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'azure/gpt-4-32k' as const,
            type: 'chat',
            inputCost: 0.00006,
            inputCostUnit: 'token',
            outputCost: 0.00012,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'azure/gpt-4' as const,
            type: 'chat',
            inputCost: 0.00003,
            inputCostUnit: 'token',
            outputCost: 0.00006,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 128000,
            name: 'azure/gpt-4-turbo' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 128000,
            name: 'azure/gpt-4-turbo-vision-preview' as const,
            type: 'chat',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00003,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16385,
            name: 'azure/gpt-35-turbo-16k-0613' as const,
            type: 'chat',
            inputCost: 0.000003,
            inputCostUnit: 'token',
            outputCost: 0.000004,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16384,
            name: 'azure/gpt-35-turbo-1106' as const,
            type: 'chat',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16385,
            name: 'azure/gpt-35-turbo-16k' as const,
            type: 'chat',
            inputCost: 0.000003,
            inputCostUnit: 'token',
            outputCost: 0.000004,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4097,
            name: 'azure/gpt-35-turbo' as const,
            type: 'chat',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8191,
            name: 'azure/ada' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 8191,
            name: 'azure/text-embedding-ada-002' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
    ],
    'text-completion-openai': [
        {
            maxTokens: 16384,
            name: 'babbage-002' as const,
            type: 'completion',
            inputCost: 4e-7,
            inputCostUnit: 'token',
            outputCost: 4e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16384,
            name: 'davinci-002' as const,
            type: 'completion',
            inputCost: 0.000002,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'gpt-3.5-turbo-instruct' as const,
            type: 'completion',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
    ],
    'anthropic': [
        {
            maxTokens: 100000,
            name: 'claude-instant-1' as const,
            type: 'chat',
            inputCost: 0.00000163,
            inputCostUnit: 'token',
            outputCost: 0.00000551,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'claude-instant-1.2' as const,
            type: 'chat',
            inputCost: 1.63e-7,
            inputCostUnit: 'token',
            outputCost: 5.51e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'claude-2' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 200000,
            name: 'claude-2.1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
    ],
    'mistral': [
        {
            maxTokens: 8192,
            name: 'mistral/mistral-tiny' as const,
            type: 'chat',
            inputCost: 1.5e-7,
            inputCostUnit: 'token',
            outputCost: 4.6e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'mistral/mistral-small' as const,
            type: 'chat',
            inputCost: 6.6e-7,
            inputCostUnit: 'token',
            outputCost: 0.00000197,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'mistral/mistral-medium' as const,
            type: 'chat',
            inputCost: 0.00000273,
            inputCostUnit: 'token',
            outputCost: 0.0000082,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'mistral/mistral-embed' as const,
            type: 'embedding',
            inputCost: 1.11e-7,
            inputCostUnit: 'token',
            outputCost: null,
            outputCostUnit: null,
        },
    ],
    'vertex-ai': [
        {
            maxTokens: 8192,
            name: 'text-bison' as const,
            type: 'completion',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'text-bison@001' as const,
            type: 'completion',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'text-unicorn' as const,
            type: 'completion',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.000028,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'text-unicorn@001' as const,
            type: 'completion',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.000028,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'chat-bison' as const,
            type: 'chat',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'chat-bison@001' as const,
            type: 'chat',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'chat-bison@002' as const,
            type: 'chat',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32000,
            name: 'chat-bison-32k' as const,
            type: 'chat',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 6144,
            name: 'code-bison' as const,
            type: 'chat',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 6144,
            name: 'code-bison@001' as const,
            type: 'completion',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'code-gecko@001' as const,
            type: 'completion',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'code-gecko@002' as const,
            type: 'completion',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'code-gecko' as const,
            type: 'completion',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32760,
            name: 'gemini-pro' as const,
            type: 'chat',
            inputCost: 2.5e-7,
            inputCostUnit: 'token',
            outputCost: 5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32760,
            name: 'gemini-1.0-pro' as const,
            type: 'chat',
            inputCost: 2.5e-7,
            inputCostUnit: 'token',
            outputCost: 5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16384,
            name: 'gemini-pro-vision' as const,
            type: 'chat',
            inputCost: 2.5e-7,
            inputCostUnit: 'token',
            outputCost: 5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16384,
            name: 'gemini-1.0-pro-vision' as const,
            type: 'chat',
            inputCost: 2.5e-7,
            inputCostUnit: 'token',
            outputCost: 5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 3072,
            name: 'textembedding-gecko' as const,
            type: 'embedding',
            inputCost: 6.25e-9,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 3072,
            name: 'textembedding-gecko-multilingual' as const,
            type: 'embedding',
            inputCost: 6.25e-9,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 3072,
            name: 'textembedding-gecko-multilingual@001' as const,
            type: 'embedding',
            inputCost: 6.25e-9,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 3072,
            name: 'textembedding-gecko@001' as const,
            type: 'embedding',
            inputCost: 6.25e-9,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 3072,
            name: 'textembedding-gecko@003' as const,
            type: 'embedding',
            inputCost: 6.25e-9,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
    ],
    'vertex_ai-code-chat-models': [
        {
            maxTokens: 6144,
            name: 'codechat-bison' as const,
            type: 'chat',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 6144,
            name: 'codechat-bison@001' as const,
            type: 'chat',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32000,
            name: 'codechat-bison-32k' as const,
            type: 'chat',
            inputCost: 1.25e-7,
            inputCostUnit: 'token',
            outputCost: 1.25e-7,
            outputCostUnit: 'token',
        },
    ],
    'cohere': [
        {
            maxTokens: 4096,
            name: 'command-nightly' as const,
            type: 'completion',
            inputCost: 0.000015,
            inputCostUnit: 'token',
            outputCost: 0.000015,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'command' as const,
            type: 'completion',
            inputCost: 0.000015,
            inputCostUnit: 'token',
            outputCost: 0.000015,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'command-light' as const,
            type: 'completion',
            inputCost: 0.000015,
            inputCostUnit: 'token',
            outputCost: 0.000015,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'command-medium-beta' as const,
            type: 'completion',
            inputCost: 0.000015,
            inputCostUnit: 'token',
            outputCost: 0.000015,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'command-xlarge-beta' as const,
            type: 'completion',
            inputCost: 0.000015,
            inputCostUnit: 'token',
            outputCost: 0.000015,
            outputCostUnit: 'token',
        },
    ],
    'replicate': [
        {
            maxTokens: 4096,
            name: 'replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1' as const,
            type: 'chat',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
    ],
    'openrouter': [
        {
            maxTokens: 4095,
            name: 'openrouter/openai/gpt-3.5-turbo' as const,
            type: 'chat',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16383,
            name: 'openrouter/openai/gpt-3.5-turbo-16k' as const,
            type: 'chat',
            inputCost: 0.000003,
            inputCostUnit: 'token',
            outputCost: 0.000004,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'openrouter/openai/gpt-4' as const,
            type: 'chat',
            inputCost: 0.00003,
            inputCostUnit: 'token',
            outputCost: 0.00006,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'openrouter/anthropic/claude-instant-v1' as const,
            type: 'chat',
            inputCost: 0.00000163,
            inputCostUnit: 'token',
            outputCost: 0.00000551,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'openrouter/anthropic/claude-2' as const,
            type: 'chat',
            inputCost: 0.00001102,
            inputCostUnit: 'token',
            outputCost: 0.00003268,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8000,
            name: 'openrouter/google/palm-2-chat-bison' as const,
            type: 'chat',
            inputCost: 5e-7,
            inputCostUnit: 'token',
            outputCost: 5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8000,
            name: 'openrouter/google/palm-2-codechat-bison' as const,
            type: 'chat',
            inputCost: 5e-7,
            inputCostUnit: 'token',
            outputCost: 5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'openrouter/meta-llama/llama-2-13b-chat' as const,
            type: 'chat',
            inputCost: 2e-7,
            inputCostUnit: 'token',
            outputCost: 2e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'openrouter/meta-llama/llama-2-70b-chat' as const,
            type: 'chat',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.0000015,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8096,
            name: 'openrouter/meta-llama/codellama-34b-instruct' as const,
            type: 'chat',
            inputCost: 5e-7,
            inputCostUnit: 'token',
            outputCost: 5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'openrouter/nousresearch/nous-hermes-llama2-13b' as const,
            type: 'chat',
            inputCost: 2e-7,
            inputCostUnit: 'token',
            outputCost: 2e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8000,
            name: 'openrouter/mancer/weaver' as const,
            type: 'chat',
            inputCost: 0.000005625,
            inputCostUnit: 'token',
            outputCost: 0.000005625,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'openrouter/gryphe/mythomax-l2-13b' as const,
            type: 'chat',
            inputCost: 0.000001875,
            inputCostUnit: 'token',
            outputCost: 0.000001875,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'openrouter/jondurbin/airoboros-l2-70b-2.1' as const,
            type: 'chat',
            inputCost: 0.000013875,
            inputCostUnit: 'token',
            outputCost: 0.000013875,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 6144,
            name: 'openrouter/undi95/remm-slerp-l2-13b' as const,
            type: 'chat',
            inputCost: 0.000001875,
            inputCostUnit: 'token',
            outputCost: 0.000001875,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'openrouter/pygmalionai/mythalion-13b' as const,
            type: 'chat',
            inputCost: 0.000001875,
            inputCostUnit: 'token',
            outputCost: 0.000001875,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'openrouter/mistralai/mistral-7b-instruct' as const,
            type: 'chat',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
    ],
    'ai21': [
        {
            maxTokens: 8192,
            name: 'j2-ultra' as const,
            type: 'completion',
            inputCost: 0.000015,
            inputCostUnit: 'token',
            outputCost: 0.000015,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'j2-mid' as const,
            type: 'completion',
            inputCost: 0.00001,
            inputCostUnit: 'token',
            outputCost: 0.00001,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'j2-light' as const,
            type: 'completion',
            inputCost: 0.000003,
            inputCostUnit: 'token',
            outputCost: 0.000003,
            outputCostUnit: 'token',
        },
    ],
    'nlp_cloud': [
        {
            maxTokens: 4096,
            name: 'dolphin' as const,
            type: 'completion',
            inputCost: 0.00002,
            inputCostUnit: 'token',
            outputCost: 0.00002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'chatdolphin' as const,
            type: 'chat',
            inputCost: 0.00002,
            inputCostUnit: 'token',
            outputCost: 0.00002,
            outputCostUnit: 'token',
        },
    ],
    'aleph_alpha': [
        {
            maxTokens: 2048,
            name: 'luminous-base' as const,
            type: 'completion',
            inputCost: 0.00003,
            inputCostUnit: 'token',
            outputCost: 0.000033,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'luminous-base-control' as const,
            type: 'chat',
            inputCost: 0.0000375,
            inputCostUnit: 'token',
            outputCost: 0.00004125,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'luminous-extended' as const,
            type: 'completion',
            inputCost: 0.000045,
            inputCostUnit: 'token',
            outputCost: 0.0000495,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'luminous-extended-control' as const,
            type: 'chat',
            inputCost: 0.00005625,
            inputCostUnit: 'token',
            outputCost: 0.000061875,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'luminous-supreme' as const,
            type: 'completion',
            inputCost: 0.000175,
            inputCostUnit: 'token',
            outputCost: 0.0001925,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'luminous-supreme-control' as const,
            type: 'chat',
            inputCost: 0.00021875,
            inputCostUnit: 'token',
            outputCost: 0.000240625,
            outputCostUnit: 'token',
        },
    ],
    'bedrock': [
        {
            maxTokens: 8191,
            name: 'ai21.j2-mid-v1' as const,
            type: 'chat',
            inputCost: 0.0000125,
            inputCostUnit: 'token',
            outputCost: 0.0000125,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8191,
            name: 'ai21.j2-ultra-v1' as const,
            type: 'chat',
            inputCost: 0.0000188,
            inputCostUnit: 'token',
            outputCost: 0.0000188,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8000,
            name: 'amazon.titan-text-lite-v1' as const,
            type: 'chat',
            inputCost: 3e-7,
            inputCostUnit: 'token',
            outputCost: 4e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8000,
            name: 'amazon.titan-text-express-v1' as const,
            type: 'chat',
            inputCost: 0.0000013,
            inputCostUnit: 'token',
            outputCost: 0.0000017,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'amazon.titan-embed-text-v1' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/1-month-commitment/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/6-month-commitment/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/1-month-commitment/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/6-month-commitment/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/1-month-commitment/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/6-month-commitment/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/1-month-commitment/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/6-month-commitment/anthropic.claude-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/1-month-commitment/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/6-month-commitment/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/1-month-commitment/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/6-month-commitment/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/1-month-commitment/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/6-month-commitment/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/1-month-commitment/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/6-month-commitment/anthropic.claude-v2' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 200000,
            name: 'anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/1-month-commitment/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/6-month-commitment/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: 0.000008,
            inputCostUnit: 'token',
            outputCost: 0.000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/1-month-commitment/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/6-month-commitment/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/1-month-commitment/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/6-month-commitment/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/1-month-commitment/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/6-month-commitment/anthropic.claude-v2:1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: 0.00000163,
            inputCostUnit: 'token',
            outputCost: 0.00000551,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: 8e-7,
            inputCostUnit: 'token',
            outputCost: 0.0000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/1-month-commitment/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-east-1/6-month-commitment/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/1-month-commitment/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/6-month-commitment/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/us-west-2/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: 8e-7,
            inputCostUnit: 'token',
            outputCost: 0.0000024,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: 0.00000223,
            inputCostUnit: 'token',
            outputCost: 0.00000755,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/1-month-commitment/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/ap-northeast-1/6-month-commitment/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: 0.00000248,
            inputCostUnit: 'token',
            outputCost: 0.00000838,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/1-month-commitment/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 100000,
            name: 'bedrock/eu-central-1/6-month-commitment/anthropic.claude-instant-v1' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'cohere.command-text-v14' as const,
            type: 'chat',
            inputCost: 0.0000015,
            inputCostUnit: 'token',
            outputCost: 0.000002,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'bedrock/*/1-month-commitment/cohere.command-text-v14' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'bedrock/*/6-month-commitment/cohere.command-text-v14' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 4000,
            name: 'cohere.command-light-text-v14' as const,
            type: 'chat',
            inputCost: 3e-7,
            inputCostUnit: 'token',
            outputCost: 6e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'bedrock/*/1-month-commitment/cohere.command-light-text-v14' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'bedrock/*/6-month-commitment/cohere.command-light-text-v14' as const,
            type: 'chat',
            inputCost: null,
            inputCostUnit: null,
            outputCost: null,
            outputCostUnit: null,
        },
        {
            maxTokens: 512,
            name: 'cohere.embed-english-v3' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 512,
            name: 'cohere.embed-multilingual-v3' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'meta.llama2-13b-chat-v1' as const,
            type: 'chat',
            inputCost: 7.5e-7,
            inputCostUnit: 'token',
            outputCost: 0.000001,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'meta.llama2-70b-chat-v1' as const,
            type: 'chat',
            inputCost: 0.00000195,
            inputCostUnit: 'token',
            outputCost: 0.00000256,
            outputCostUnit: 'token',
        },
    ],
    'sagemaker': [
        {
            maxTokens: 4096,
            name: 'sagemaker/meta-textgeneration-llama-2-7b' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'sagemaker/meta-textgeneration-llama-2-7b-f' as const,
            type: 'chat',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'sagemaker/meta-textgeneration-llama-2-13b' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'sagemaker/meta-textgeneration-llama-2-13b-f' as const,
            type: 'chat',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'sagemaker/meta-textgeneration-llama-2-70b' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'sagemaker/meta-textgeneration-llama-2-70b-b-f' as const,
            type: 'chat',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
    ],
    'ollama': [
        {
            maxTokens: 4096,
            name: 'ollama/llama2' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'ollama/llama2:13b' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'ollama/llama2:70b' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'ollama/llama2-uncensored' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 8192,
            name: 'ollama/mistral' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'ollama/codellama' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'ollama/orca-mini' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 2048,
            name: 'ollama/vicuna' as const,
            type: 'completion',
            inputCost: 0,
            inputCostUnit: null,
            outputCost: 0,
            outputCostUnit: null,
        },
    ],
    'deepinfra': [
        {
            maxTokens: 4096,
            name: 'deepinfra/lizpreciatior/lzlv_70b_fp16_hf' as const,
            type: 'chat',
            inputCost: 7e-7,
            inputCostUnit: 'token',
            outputCost: 9e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/Gryphe/MythoMax-L2-13b' as const,
            type: 'chat',
            inputCost: 2.2e-7,
            inputCostUnit: 'token',
            outputCost: 2.2e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'deepinfra/mistralai/Mistral-7B-Instruct-v0.1' as const,
            type: 'chat',
            inputCost: 1.3e-7,
            inputCostUnit: 'token',
            outputCost: 1.3e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/meta-llama/Llama-2-70b-chat-hf' as const,
            type: 'chat',
            inputCost: 7e-7,
            inputCostUnit: 'token',
            outputCost: 9e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'deepinfra/cognitivecomputations/dolphin-2.6-mixtral-8x7b' as const,
            type: 'chat',
            inputCost: 2.7e-7,
            inputCostUnit: 'token',
            outputCost: 2.7e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/codellama/CodeLlama-34b-Instruct-hf' as const,
            type: 'chat',
            inputCost: 6e-7,
            inputCostUnit: 'token',
            outputCost: 6e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/deepinfra/mixtral' as const,
            type: 'completion',
            inputCost: 2.7e-7,
            inputCostUnit: 'token',
            outputCost: 2.7e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/Phind/Phind-CodeLlama-34B-v2' as const,
            type: 'chat',
            inputCost: 6e-7,
            inputCostUnit: 'token',
            outputCost: 6e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'deepinfra/mistralai/Mixtral-8x7B-Instruct-v0.1' as const,
            type: 'chat',
            inputCost: 2.7e-7,
            inputCostUnit: 'token',
            outputCost: 2.7e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/deepinfra/airoboros-70b' as const,
            type: 'chat',
            inputCost: 7e-7,
            inputCostUnit: 'token',
            outputCost: 9e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/01-ai/Yi-34B-Chat' as const,
            type: 'chat',
            inputCost: 6e-7,
            inputCostUnit: 'token',
            outputCost: 6e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/01-ai/Yi-6B-200K' as const,
            type: 'completion',
            inputCost: 1.3e-7,
            inputCostUnit: 'token',
            outputCost: 1.3e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/jondurbin/airoboros-l2-70b-gpt4-1.4.1' as const,
            type: 'chat',
            inputCost: 7e-7,
            inputCostUnit: 'token',
            outputCost: 9e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/meta-llama/Llama-2-13b-chat-hf' as const,
            type: 'chat',
            inputCost: 2.2e-7,
            inputCostUnit: 'token',
            outputCost: 2.2e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 32768,
            name: 'deepinfra/amazon/MistralLite' as const,
            type: 'chat',
            inputCost: 2e-7,
            inputCostUnit: 'token',
            outputCost: 2e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/meta-llama/Llama-2-7b-chat-hf' as const,
            type: 'chat',
            inputCost: 1.3e-7,
            inputCostUnit: 'token',
            outputCost: 1.3e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/01-ai/Yi-34B-200K' as const,
            type: 'completion',
            inputCost: 6e-7,
            inputCostUnit: 'token',
            outputCost: 6e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'deepinfra/openchat/openchat_3.5' as const,
            type: 'chat',
            inputCost: 1.3e-7,
            inputCostUnit: 'token',
            outputCost: 1.3e-7,
            outputCostUnit: 'token',
        },
    ],
    'perplexity': [
        {
            maxTokens: 16384,
            name: 'perplexity/codellama-34b-instruct' as const,
            type: 'chat',
            inputCost: 3.5e-7,
            inputCostUnit: 'token',
            outputCost: 0.0000014,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16384,
            name: 'perplexity/codellama-70b-instruct' as const,
            type: 'chat',
            inputCost: 7e-7,
            inputCostUnit: 'token',
            outputCost: 0.0000028,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'perplexity/pplx-7b-chat' as const,
            type: 'chat',
            inputCost: 7e-8,
            inputCostUnit: 'token',
            outputCost: 2.8e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'perplexity/pplx-70b-chat' as const,
            type: 'chat',
            inputCost: 7e-7,
            inputCostUnit: 'token',
            outputCost: 0.0000028,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'perplexity/pplx-7b-online' as const,
            type: 'chat',
            inputCost: 0,
            inputCostUnit: 'request',
            outputCost: 2.8e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'perplexity/pplx-70b-online' as const,
            type: 'chat',
            inputCost: 0,
            inputCostUnit: 'request',
            outputCost: 0.0000028,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'perplexity/llama-2-70b-chat' as const,
            type: 'chat',
            inputCost: 7e-7,
            inputCostUnit: 'token',
            outputCost: 0.0000028,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'perplexity/mistral-7b-instruct' as const,
            type: 'chat',
            inputCost: 7e-8,
            inputCostUnit: 'token',
            outputCost: 2.8e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'perplexity/mixtral-8x7b-instruct' as const,
            type: 'chat',
            inputCost: 7e-8,
            inputCostUnit: 'token',
            outputCost: 2.8e-7,
            outputCostUnit: 'token',
        },
    ],
    'anyscale': [
        {
            maxTokens: 16384,
            name: 'anyscale/mistralai/Mistral-7B-Instruct-v0.1' as const,
            type: 'chat',
            inputCost: 1.5e-7,
            inputCostUnit: 'token',
            outputCost: 1.5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16384,
            name: 'anyscale/HuggingFaceH4/zephyr-7b-beta' as const,
            type: 'chat',
            inputCost: 1.5e-7,
            inputCostUnit: 'token',
            outputCost: 1.5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'anyscale/meta-llama/Llama-2-7b-chat-hf' as const,
            type: 'chat',
            inputCost: 1.5e-7,
            inputCostUnit: 'token',
            outputCost: 1.5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'anyscale/meta-llama/Llama-2-13b-chat-hf' as const,
            type: 'chat',
            inputCost: 2.5e-7,
            inputCostUnit: 'token',
            outputCost: 2.5e-7,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'anyscale/meta-llama/Llama-2-70b-chat-hf' as const,
            type: 'chat',
            inputCost: 0.000001,
            inputCostUnit: 'token',
            outputCost: 0.000001,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 16384,
            name: 'anyscale/codellama/CodeLlama-34b-Instruct-hf' as const,
            type: 'chat',
            inputCost: 0.000001,
            inputCostUnit: 'token',
            outputCost: 0.000001,
            outputCostUnit: 'token',
        },
    ],
    'cloudflare': [
        {
            maxTokens: 3072,
            name: 'cloudflare/@cf/meta/llama-2-7b-chat-fp16' as const,
            type: 'chat',
            inputCost: 0.000001923,
            inputCostUnit: 'token',
            outputCost: 0.000001923,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 2048,
            name: 'cloudflare/@cf/meta/llama-2-7b-chat-int8' as const,
            type: 'chat',
            inputCost: 0.000001923,
            inputCostUnit: 'token',
            outputCost: 0.000001923,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 8192,
            name: 'cloudflare/@cf/mistral/mistral-7b-instruct-v0.1' as const,
            type: 'chat',
            inputCost: 0.000001923,
            inputCostUnit: 'token',
            outputCost: 0.000001923,
            outputCostUnit: 'token',
        },
        {
            maxTokens: 4096,
            name: 'cloudflare/@hf/thebloke/codellama-7b-instruct-awq' as const,
            type: 'chat',
            inputCost: 0.000001923,
            inputCostUnit: 'token',
            outputCost: 0.000001923,
            outputCostUnit: 'token',
        },
    ],
    'voyage': [
        {
            maxTokens: 4096,
            name: 'voyage/voyage-01' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
        {
            maxTokens: 4096,
            name: 'voyage/voyage-lite-01' as const,
            type: 'embedding',
            inputCost: 1e-7,
            inputCostUnit: 'token',
            outputCost: 0,
            outputCostUnit: null,
        },
    ],
} as const
